### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by utixx** [mribrahim/inception-unet#1]
when running the code，a problem happen:  

len train  5390
Traceback (most recent call last):
  File "E:/Pycharm/ML/inception-unet/train.py", line 64, in <module>
    x_valid, y_valid = read_data.read(path, 4)
  File "E:\Pycharm\ML\inception-unet\read_data.py", line 62, in read
    Ytrain[index,:,:] = image_label.copy()
IndexError: index 196 is out of bounds for axis 0 with size 196

**Comment by mribrahim** [comment]
Validation data includes 4 images in Massachusetts dataset. We extract 49 subset images from each 1500x1500 dimension image, and totally 196 small patches for validation. So last index value is 195 and 196 is out of bounds as in your error message. I tried to run the code and it is working, maybe you have made an update over code?

**Comment by utixx** [comment]
> Validation data includes 4 images in Massachusetts dataset. We extract 49 subset images from each 1500x1500 dimension image, and totally 196 small patches for validation. So last index value is 195 and 196 is out of bounds as in your error message. I tried to run the code and it is working, maybe you have made an update over code?

guess I know what it is. Thx alot !!!
